Add parameters for basic handling of mods
acemod/docker-reforger pull request #11
Opened 2022-05-30 16:23 UTC by sdsznsk

2022-05-30 16:26 UTC, sdsznsk commented
Also, one question to which I probably know an answer but want to ask first- do we want safeguards (like check if both mutually exclusive are defined)? I saw that there are next to no checks for params so...

2022-05-30 17:34 UTC, veteran29 commented
LGTM but I don't know Python so leaving the approval to someone else 😁

2022-05-30 18:45 UTC, BrettMayson commented
Could allow JSON and the IDs in the env, load the json first then append from env

2022-05-30 18:52 UTC, sdsznsk commented
Sounds good, will do

2022-05-30 21:01 UTC, Dahlgren commented
Name is only for human readability and not needed by the server.

I suggest we only use one environment variable to specify mods, `GAME_MODS`, which accepts either any version of specific version.

1. Mods with any versions, `GAME_MODS=5965770215E93269,59664C0CB36501CD`
2. Mods with specific versions, `GAME_MODS=5965770215E93269=1.0.6,59664C0CB36501CD=0.3.0`
3. Mods with any and specific versions, `GAME_MODS=5965770215E93269,59664C0CB36501CD=0.3.0`

2022-05-30 21:02 UTC, Dahlgren commented
Workshop should use a volume to avoid redownload when container is recreated, for example `VOLUME /reforger/workshop`

To use the volume and separate workshop folder start the game with argument `-addonDownloadDir /reforger/workshop`

2022-05-31 13:00 UTC, sdsznsk commented
While I do agree with an option for specifying mod version in the GAME_MODS_IDS_LIST, and keeping them on a dedicated volume, I don't think removing an option to provide mods via a file is a good idea tbh. Managing dozens of mods only via one long ENV would be quite a pain. Your call tho

2022-05-31 13:14 UTC, sdsznsk commented on launch.py
> +            assert 0 < len(mod_details) < 3, f"{mod} mod not defined properly"
Converted all to `assert` statements

2022-06-10 12:19 UTC, BrettMayson approved these changes

2023-09-12 14:09 UTC, jonpas requested changes

2023-09-12 14:09 UTC, jonpas commented on README.md
> +path to a JSON file that contains array of mod objects, for example
```suggestion
Path to a JSON file that contains array of mod objects.
```

2023-09-12 14:09 UTC, jonpas commented on README.md
> +a comma separated list of IDs, with an optional version, for example
```suggestion
A comma separated list of IDs, with an optional version.
```

2023-09-22 16:39 UTC, sdsznsk commented on launch.py
> +                config["game"]["mods"].append(mod)
Added in https://github.com/acemod/docker-reforger/pull/11/commits/2a059d5bd40e5a82c724502893d0e7590ccd015d

2023-11-01 12:27 UTC, jonpas approved these changes

2023-11-01 12:27 UTC, jonpas commented
@Dahlgren re-review please.

2023-11-01 12:32 UTC, Dahlgren approved these changes
LGTM!

2023-11-01 12:34 UTC, sdsznsk commented
Lint failed though, I will take a look in an hr or two 👀

2023-11-03 18:28 UTC, merged